name: Code for Beijing Legal Hackers
url: https://legalhackersbeijing.github.io
baseurl: /beijinglegalhackers
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/blog/:num"
gems:
- jekyll-sitemap
collections:
    resources:
        output: true
exclude:
- vendor
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
